### ISSUE TITLE
`Cannot read property '[object Array]' of undefined` when using sharp notes

### ISSUE THREAD

**Issue by gregoriB** [harrylincoln/notate#11]
Tab does not generate.  I don't know much about reading music, but if there is a reason for this, then this should be expressed in the UI design or better explaining in error alert.

**Comment by harrylincoln** [comment]
Hi there! Thanks for your comment! 

Can you post steps to replicate please? That would be great!

**Comment by harrylincoln** [comment]
@gregoriB I believe to this be fixed - the error I believe was caused by a spoofed note value push.

The sorting algorithm will try and mutate the notes to a given key, and in the process, it would sometimes aug or dim a note to something that didn't exist, or wasn't defined since it's not a 'real' note (C-> Cb // E->E#). 

Please have a test on the site and let me know if still an issue 👊

**Comment by gregoriB** [comment]
Nice it seems to be fine now.
